name: C/C++ CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install ncurses
      run: sudo apt-get install libncurses5-dev libncursesw5-dev -y
    - name: make
      run: make all -j
    - name: make check
      run: make check
